# docker compose up -d
# docker compose down -rmi all -v
version: 'v1'

services:
  # データベースコンテナ
  db:
    image: mariadb:10.7
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USERNAME}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3306
    healthcheck:
      test: "mysql --password=${MYSQL_ROOT_PASSWORD} --execute 'show databases;'"

  # サーバコンテナ
  server:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  db-data:
