# docker compose up -d
# docker compose down --rmi all -v

services:
  # データベースコンテナ
  db:
    image: mariadb:10.7
    env_file: ./.db.env
    environment:
      TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3306
    healthcheck:
      test: "mysql --password=${MYSQL_PASSWORD} --execute 'show databases;'"

  # サーバコンテナ
  server:
    build: ghcr.io/meikoudai-keijiban/nitech-community_server:latest
    env_file: ./.env
    environment:
      TZ: Asia/Tokyo
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'

volumes:
  db-data:
